{ config, lib, flake, ... }:
let
  cfg = config.my.services.mailFilter;
  confDir = ".config/mail-filter";

  # Escape a Sieve string literal (only " and \ need escaping).
  esc = s: builtins.replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] s;
  q = s: "\"${esc s}\"";

  # NOTE: no parens around the test itself — `anyof (t1, t2)` requires the
  # tests bare; pigeonhole rejects `anyof ((header ...), ...)`.
  matcherCond = m: "header :contains [ \"From\", \"Subject\", \"List-Id\" ] ${q m}";

  tagRule = name: tag:
    let
      matchers = tag.matchers or [ ];
    in
    if matchers == [ ] then
      "# ${name}: no matchers (manual sorting)\n"
    else
      ''
        # ${name}
        if anyof (${lib.concatStringsSep ", " (map matcherCond matchers)}) {
          fileinto ${q tag.path};
          stop;
        }
      '';

  sieveScript = ''
    require ["fileinto", "envelope", "subaddress"];

    # Generated by my.services.mailFilter from the canonical mail taxonomy.
    ${lib.concatStrings (lib.mapAttrsToList tagRule cfg.tags)}
    ${cfg.filter.extraSieve}
  '';

  username = (flake.config.me or { }).username or "seanc";
  homeDir = "/home/${username}";

  # Classic (Dovecot 2.3 / pigeonhole 0.5) config syntax — deliberately NOT the
  # dovecot 2.4 format, because nixpkgs' dovecot_pigeonhole 2.4.x does not
  # register its `sieve` settings struct for the CLI tools (sievec/sieve-filter
  # fail config parse with "Unknown section name: sieve"). Old config is
  # understood by doveconf and the tools without any version gymnastics.
  dovecotConf = ''
    # Minimal Dovecot config for pigeonhole's sieve-filter(1).
    # Dovecot layout 'fs' + maildir root = INBOX, which matches the mbsync
    # layout created by this module (extraConfig.local.Inbox = maildir root):
    #   INBOX      = ${cfg.maildir}          (root: cur/new/tmp)
    #   subfolders = ${cfg.maildir}/<path>   (e.g. Security/1Password)
    mail_location = maildir:${cfg.maildir}:LAYOUT=fs

    namespace inbox {
      separator = /
      inbox = yes
      prefix =
    }

    userdb {
      driver = static
      args = uid=${username} gid=users home=${homeDir}
    }
  '';
in
{
  config = lib.mkIf cfg.enable {
    home.file."${confDir}/filter.sieve".text = sieveScript;
    home.file."${confDir}/dovecot.conf".text = dovecotConf;
  };
}