# Generate pyproject.toml from Nix configuration
{ pkgs, cfg, lib }:
let
  # Build pyproject.toml structure
  attrs = {
    build-system = {
      requires = [ "hatchling>=1.18.0" ];
      build-backend = "hatchling.build";
    };

    project = {
      name = cfg.name;
      version = cfg.version;
      description = cfg.description;
      readme = cfg.readme;
      requires-python = cfg.requiresPython;
      dependencies = cfg.dependencies;
      scripts = cfg.scripts;
    } // lib.optionalAttrs (cfg.optionalDependencies != { }) {
      optional-dependencies = cfg.optionalDependencies;
    };

    # Dev dependencies group (PEP 735)
    dependency-groups = lib.optionalAttrs (cfg.devDependencies != [ ]) {
      dev = cfg.devDependencies;
    };

    # Hatch build targets — tells hatchling to look for packages under src/
    tool.hatch.build.targets.wheel = {
      packages = [ "src/${cfg.name}" ];
    };

    # Ruff configuration
    tool.ruff = {
      line-length = 100;
      target-version = "py312";
    };

    tool.ruff.lint = {
      select = [ "E" "F" "I" "UP" ];
      ignore = [ "E501" ]; # Line too long (handled by formatter)
    };

    # Pytest configuration
    tool.pytest = lib.optionalAttrs (lib.elem "pytest" cfg.devDependencies) {
      ini_options = {
        testpaths = [ "tests" ];
        python_files = [ "test_*.py" "*_test.py" ];
        python_classes = [ "Test*" ];
        python_functions = [ "test_*" ];
      };
    };

    # Coverage configuration
    tool.coverage = lib.optionalAttrs (lib.elem "pytest-cov" cfg.devDependencies) {
      run = {
        source = [ cfg.name ];
        omit = [ "tests/*" "*/conftest.py" ];
      };
      report = {
        show_missing = true;
        skip_covered = false;
      };
    };
  };

  # Convert to JSON for processing
  jsonData = pkgs.writeText "pyproject-data.json" (builtins.toJSON attrs);

  # Python script to generate TOML
  writerPy = pkgs.writeText "write-pyproject.py" ''
    import json
    import sys
    from pathlib import Path


    def to_toml_value(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        elif isinstance(v, (int, float)):
            return str(v)
        elif isinstance(v, str):
            return json.dumps(v)
        elif isinstance(v, list):
            if not v:
                return "[]"
            if all(isinstance(i, (str, bool, int, float)) for i in v):
                items = [to_toml_value(i) for i in v]
                return "[" + ", ".join(items) + "]"
            lines = ["["]
            for item in v:
                lines.append("    " + to_toml_value(item) + ",")
            lines.append("]")
            return "\n".join(lines)
        elif isinstance(v, dict):
            return None
        else:
            return json.dumps(str(v))


    def write_inline_table(d, indent=0):
        if not d:
            return "{}"
        items = []
        for k, v in d.items():
            if isinstance(v, dict):
                items.append(f"{k} = {write_inline_table(v, indent + 4)}")
            else:
                items.append(f"{k} = {to_toml_value(v)}")
        return "{ " + ", ".join(items) + " }"


    def write_section(out, path, value):
        if isinstance(value, dict):
            has_nested = any(isinstance(v, dict) for v in value.values())

            if not has_nested and value:
                out.append(f"[{path}]")
                for k, v in value.items():
                    out.append(f"{k} = {to_toml_value(v)}")
            else:
                scalars = {}
                for k, v in value.items():
                    if isinstance(v, dict):
                        write_section(out, f"{path}.{k}", v)
                    elif v is not None:
                        scalars[k] = v

                if scalars:
                    out.append(f"[{path}]")
                    for k, v in scalars.items():
                        out.append(f"{k} = {to_toml_value(v)}")
        else:
            out.append(f"[{path}]")
            out.append(f"value = {to_toml_value(value)}")


    def main():
        if len(sys.argv) != 3:
            print(f"Usage: {sys.argv[0]} <input.json> <output.toml>", file=sys.stderr)
            sys.exit(1)

        json_path = sys.argv[1]
        toml_path = sys.argv[2]

        with open(json_path) as f:
            data = json.load(f)

        lines = ["# Generated by flake.nix — edit in modules/flake.nix"]

        for section, value in data.items():
            if isinstance(value, dict):
                has_nested = any(isinstance(v, dict) for v in value.values())
                if not has_nested and value:
                    lines.append(f"[{section}]")
                    for k, v in value.items():
                        if v is not None:
                            lines.append(f"{k} = {to_toml_value(v)}")
                else:
                    scalars = {}
                    for k, v in value.items():
                        if isinstance(v, dict):
                            write_section(lines, f"{section}.{k}", v)
                        elif v is not None:
                            scalars[k] = v
                    if scalars:
                        lines.append(f"[{section}]")
                        for k, v in scalars.items():
                            lines.append(f"{k} = {to_toml_value(v)}")
            else:
                lines.append(f"{section} = {to_toml_value(value)}")

        output = "\n".join(lines) + "\n"
        Path(toml_path).write_text(output)
        print(f"Generated {toml_path}")


    if __name__ == "__main__":
        main()
  '';

in
{
  inherit jsonData writerPy;
}
