name = "AllTheTech"
author = "Cairnstew"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6660c278e9511f71009f7c13c5c72fbde4b9e8b9c9beebadb29e0bb3877c9935"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
datapack-folder = "config/paxi/datapacks"
