name = "AllTheTech"
author = "Cairnstew"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2802832c1aa89165a7b639a75979c836cd684d6c3b897140f6f9c1669a61c4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
datapack-folder = "config/paxi/datapacks"
