# Wires my.services.minecraftServer into services.minecraft-servers (nix-minecraft).
{ config, lib, flake, pkgs, ... }:

let
  inherit (lib) mkIf mkMerge mapAttrs' nameValuePair concatStringsSep optionalAttrs;
  inherit (flake) inputs;
  inherit (inputs) nix-minecraft packwiz2nix nixos-minecraft-modpacks;
  me = flake.config.me;

  cfg = config.my.services.minecraftServer;

  # Content subdirectories a modpack zip can carry. `world*` is deliberately
  # excluded — a live world comes from migrateFrom or is freshly generated, and
  # must never be clobbered by a pack zip.
  packSubdirs = [ "mods" "config" "kubejs" "scripts" "datapacks" "defaultconfigs" ];

  # ── Content source: packZip (zip dropped in packDir) ──────────────────────
  # Extracts the zip into <dataDir>/<name>/.mc-pack only when its SHA-256
  # changes (stamped), then symlinks the content subdirs into the data dir. A
  # Prism instance zip wraps `minecraft/`; an mrpack/CurseForge pack wraps
  # `overrides/`; a bare modpack zip has the dirs at the root — all three
  # layouts are detected.
  zipExtractPre = name: srv:
    if srv.packZip == null then ""
    else
      let
        zipPath =
          if lib.hasPrefix "/" srv.packZip then srv.packZip
          else "${cfg.packDir}/${srv.packZip}";
        staging = "${cfg.dataDir}/${name}/.mc-pack";
        stamp = "${staging}.stamp";
      in
      ''
        ZIP='${zipPath}'
        STAGING='${staging}'
        STAMP='${stamp}'
        ROOT=""
        if [ ! -f "$ZIP" ]; then
          echo "[mc] WARN: packZip $ZIP not found — starting without it" >&2
        else
          NEW=$(${pkgs.coreutils}/bin/sha256sum "$ZIP" | ${pkgs.coreutils}/bin/cut -d' ' -f1)
          OLD=$(${pkgs.coreutils}/bin/cat "$STAMP" 2>/dev/null || true)
          if [ "$NEW" != "$OLD" ]; then
            echo "[mc] unpacking $ZIP ..."
            ${pkgs.coreutils}/bin/rm -rf "$STAGING"
            ${pkgs.coreutils}/bin/mkdir -p "$STAGING"
            if ! ${pkgs.unzip}/bin/unzip -q "$ZIP" -d "$STAGING"; then
              echo "[mc] WARN: failed to unzip $ZIP — leaving old pack in place" >&2
              ${pkgs.coreutils}/bin/rm -rf "$STAGING"
            else
              # Content root: Prism instance zip → minecraft/; mrpack/CF → overrides/.
              ROOT="$STAGING"
              if [ -d "$STAGING/minecraft" ]; then ROOT="$STAGING/minecraft"; fi
              if [ -d "$STAGING/overrides" ]; then ROOT="$STAGING/overrides"; fi
              if [ -d "$ROOT" ]; then
                echo "$NEW" > "$STAMP"
              fi
            fi
          fi
        fi
        # Symlink content subdirs (idempotent; no-op if unpack failed/zip missing).
        for d in ${concatStringsSep " " packSubdirs}; do
          if [ -n "$ROOT" ] && [ -d "$ROOT/$d" ]; then
            ${pkgs.coreutils}/bin/ln -sfn "$ROOT/$d" "$d"
          fi
        done
      '';

  # ── Content source: pack (plain dir or fetchModrinthModpack derivation) ───
  # Symlinked from a path on disk; placed after the zip so pack wins on conflicts.
  packStartPre = srv:
    if srv.pack == null then ""
    else
      concatStringsSep "\n" (builtins.map
        (d: ''
          if [ -d "${srv.pack}/${d}" ]; then
            ln -sfn "${srv.pack}/${d}" "${d}"
          fi
        '')
        packSubdirs);

  # ── Content source: packwiz (packwiz2nix fixed-output derivations) ────────
  # Reads <modpack>/checksums.json (generated by the
  # .#packwiz-checksums-<pack> app) and builds each mod as a fixed-output
  # derivation, symlinked into the server's mods/ via nix-minecraft's `symlinks`
  # (allowedSymlinks already permits /nix/store). Warns (and links nothing)
  # until checksums.json exists, so a fresh pack never breaks evaluation.
  packwizSymlinks = name: srv:
    if srv.packwiz == null then { }
    else if !builtins.pathExists "${srv.packwiz}/checksums.json" then
      lib.warn ''
        my.services.minecraftServer: server ${name} has packwiz = ${toString srv.packwiz}
        but no checksums.json exists yet. Generate it with
        `just packwiz-checksums <pack>` (after `packwiz init` / adding mods)
        and commit it. Starting this server without mods for now.
      ''
        { }
    else
      let
        checksums = "${srv.packwiz}/checksums.json";
        # Fixed-output derivations for every mod in checksums.json, then any
        # build-time jar patches from <pack>/patches.nix overlaid on top (same
        # mechanism as the client's mkClientInstance in modules/flake-parts/
        # packwiz.nix — one patch definition, both sides).
        mods = packwiz2nix.lib.mkPackwizPackages pkgs checksums;
        # Server-only filter: drop mods marked `side = "client"` in their
        # packwiz .pw.toml (e.g. Sodium, Iris). A client pack ships render/GL
        # mods whose PreLaunchChecks require LWJGL, which a headless server
        # lacks — linking them makes the server crash at boot with
        # NoClassDefFoundError: org/lwjgl/Version. packwiz does the same
        # filtering when installing a pack to a server.
        serverMods = lib.filterAttrs
          (name: _:
            let
              pw = "${srv.packwiz}/mods/${name}";
            in
            !builtins.pathExists pw
            || ((builtins.fromTOML (builtins.readFile pw)).side or "both") != "client"
          )
          mods;
        patchedMods =
          if builtins.pathExists "${srv.packwiz}/patches.nix" then
            import "${srv.packwiz}/patches.nix"
              {
                inherit mods pkgs;
                # patchJar/buildModSource now come from the nixos-minecraft-modpacks input
                patchJar = import "${nixos-minecraft-modpacks}/modpacks/patch-jar.nix" { inherit pkgs; };
                # Source-level jar patches (build the whole mod from source).
                buildModSource = import "${nixos-minecraft-modpacks}/modpacks/build-mod-source.nix" { inherit pkgs; };
              }
          else
            { };
        # Extra LOCAL mods that are not in checksums.json (our own source, built
        # via buildModSource — e.g. dt-tree-water-cleanup). Same caveat about
        # inputs.self for buildModSource as patches.nix above. Keys follow the
        # mkModLinks convention: "mods/<name>.jar".
        extraMods =
          if builtins.pathExists "${srv.packwiz}/extra-mods.nix" then
            import "${srv.packwiz}/extra-mods.nix"
              {
                inherit mods pkgs;
                buildModSource = import "${nixos-minecraft-modpacks}/modpacks/build-mod-source.nix" { inherit pkgs; };
              }
          else
            { };
      in
      (packwiz2nix.lib.mkModLinks serverMods) // patchedMods // extraMods;

  # Internal (non-mod) content subdirs from the packwiz pack dir. packwiz
  # installers copy these into the game folder on install; our server must do
  # the same so shipped default configs / Paxi datapacks / KubeJS & CraftTweaker
  # scripts actually reach the server. The packwiz dir is a store path, so these
  # symlinks resolve at runtime. `mods` is excluded — mods come from
  # checksums.json via packwizSymlinks above.
  #
  # `config` and `defaultconfigs` are NOT symlinked: the server writes to them at
  # boot (FML generates config/fml.toml, mods write their defaults), and a
  # symlink into the read-only store crashes with `Read-only file system`. They
  # are seeded as real dirs with rsync --ignore-existing (pack ships defaults;
  # existing/server-generated files win) — the same preserve policy the client
  # instance uses (packwiz-instance-sync.py). Everything else stays symlinked.
  packwizStartPre = srv:
    if srv.packwiz == null then ""
    else
    # `config` and `defaultconfigs` are seeded as real writable dirs (see
    # below); the rest are symlinked into the data dir.
      let
        writable = [ "config" "defaultconfigs" ];
        symlinkDirs = builtins.filter (d: d != "mods" && !builtins.elem d writable) packSubdirs;
        writableDirs = builtins.filter (d: builtins.elem d writable) packSubdirs;
      in
      concatStringsSep "\n"
        (builtins.map
          (d: ''
            if [ -d "${srv.packwiz}/${d}" ]; then
              ln -sfn "${srv.packwiz}/${d}" "${d}"
            fi
          '')
          symlinkDirs)
      # Writable dirs: the server writes to config/ (FML generates
      # config/fml.toml, mods write their defaults) and defaultconfigs/ at boot,
      # so a symlink into the read-only store crashes with `Read-only file
      # system`. Seed them as real dirs with rsync --ignore-existing (pack ships
      # defaults; existing/server-generated files win) — the same preserve
      # policy the client instance uses (packwiz-instance-sync.py). A stale
      # store symlink from the pre-writable era is removed first.
      + concatStringsSep "\n"
        (builtins.map
          (d: ''
            if [ -d "${srv.packwiz}/${d}" ]; then
              if [ -L "${d}" ]; then rm -f "${d}"; fi
              mkdir -p "${d}"
              ${pkgs.rsync}/bin/rsync -a -L --ignore-existing "${srv.packwiz}/${d}/" "${d}/"
              # The pack dir is read-only in the store; the server must be able
              # to write (FML generates config/fml.toml, mods write defaults).
              chmod -R u+w "${d}"
            fi
          '')
          writableDirs)
      # Game-root file (e.g. a shipped default options.txt) — packwiz maps a
      # pack-root file 1:1 to the game root, so symlink it the same way.
      + ''
        if [ -f "${srv.packwiz}/options.txt" ]; then
          ln -sfn "${srv.packwiz}/options.txt" "options.txt"
        fi
      '';

  # One-time world migration from an existing server-data dir (idempotent).
  migratePre = srv:
    if srv.migrateFrom == null then ""
    else ''
      if [ ! -e world ] && [ -d "${srv.migrateFrom}/world" ]; then
        echo "[mc] migrating world from ${srv.migrateFrom} ..."
        cp -a "${srv.migrateFrom}/world" world
      fi
      if [ ! -f usercache.json ] && [ -f "${srv.migrateFrom}/usercache.json" ]; then
        cp -a "${srv.migrateFrom}/usercache.json" usercache.json
      fi
    '';

  # Extra user symlinks → data dir (path → relative target in data dir).
  symlinkPre = srv:
    concatStringsSep "\n" (lib.mapAttrsToList
      (rel: src: ''
        if [ -e "${src}" ]; then
          mkdir -p "$(dirname "${rel}")"
          ln -sfn "${src}" "${rel}"
        fi
      '')
      srv.extraSymlinks);

  # ── Console management system ─────────────────────────────────────────────
  # nix-minecraft expects `managementSystem."systemd-socket".enable` (kebab),
  # our options use camelCase. Resolve effective per-server system (per-server
  # override or module-level default) and translate.
  mkManagement = srv:
    let
      eff =
        if srv.managementSystem.systemdSocket.enable || srv.managementSystem.tmux.enable
        then srv.managementSystem else cfg.managementSystem;
      useSocket = eff.systemdSocket.enable;
      sockPath = eff.systemdSocket.socketPath;
      tmuxPath = eff.tmux.socketPath;
      base =
        if useSocket then {
          "systemd-socket".enable = true;
          tmux.enable = false;
        } else {
          tmux.enable = true;
          "systemd-socket".enable = false;
        };
    in
    base
    // optionalAttrs (useSocket && sockPath != null) {
      "systemd-socket".stdinSocket.path = _: sockPath;
    }
    // optionalAttrs (!useSocket && tmuxPath != null) {
      tmux.socketPath = _: tmuxPath;
    };

  mkServer = name: srv:
    nameValuePair name {
      inherit (srv)
        enable
        package
        jvmOpts
        autoStart
        whitelist
        operators
        openFirewall
        restart
        ;
      # `server-port` from the port option unless serverProperties sets it.
      serverProperties = { "server-port" = srv.port; } // srv.serverProperties;
      managementSystem = mkManagement srv;
      symlinks = packwizSymlinks name srv;
      extraStartPre = concatStringsSep "\n" [
        (zipExtractPre name srv)
        (packStartPre srv)
        (packwizStartPre srv)
        (migratePre srv)
        (symlinkPre srv)
      ];
    };

  # Resource / scheduler caps from the per-server `hardware` option, applied to
  # the generated systemd unit, plus the OpenCL library path. nix-minecraft does
  # NOT forward arbitrary serviceConfig, so we augment the unit directly here
  # (the GOTCHAS-verified pattern). Returns the systemd.services attrset (never
  # empty — environment is always injected) for one server.
  mkHardwareServiceConfig = name: srv:
    {
      systemd.services.${"minecraft-server-${name}"} = {
        # /run/opengl-driver/lib (the NixOS graphics driver path, populated from
        # hardware.graphics.extraPackages — includes ocl-icd's libOpenCL.so.1 +
        # the NVIDIA OpenCL ICD) so c2me-ocl can reach the GPU. nix-minecraft's
        # wrapper only prepends udev, and systemd strips the ambient environment,
        # so the unit would never find libOpenCL without this. Each server drops
        # its own jvm `-Djava.library.path`; this is the dlopen path the LWJGL
        # OpenCL bindings and the ICD loader walk. Harmless on hosts without a
        # graphics stack — a missing dir just dlopens nothing and c2me-ocl falls
        # back to CPU gen.
        environment.LD_LIBRARY_PATH = lib.mkDefault "/run/opengl-driver/lib";
        serviceConfig = lib.filterAttrs (_: v: v != null) {
          MemoryMax = srv.hardware.memoryMax;
          MemoryHigh = srv.hardware.memoryHigh;
          MemorySwapMax = srv.hardware.memorySwapMax;
          CPUQuota = srv.hardware.cpuQuota;
          Nice = if srv.hardware.nice != null then toString srv.hardware.nice else null;
          IOWeight = if srv.hardware.ioWeight != null then toString srv.hardware.ioWeight else null;
          # GPU access for OpenCL worldgen (c2me-ocl): nix-minecraft hardens the
          # unit with PrivateDevices=true + DevicePolicy=closed, which mounts a
          # private /dev with NO /dev/nvidia* or /dev/dri/* nodes. OpenCL then
          # loads the ICD but finds zero platforms (CL_PLATFORM_NOT_FOUND_KHR,
          # -1001) because it cannot reach the GPU. Disable the private /dev and
          # explicitly allow the NVIDIA + DRM render nodes (harmless on hosts
          # without a GPU — the nodes just don't exist and nothing breaks).
          PrivateDevices = lib.mkForce false;
          DevicePolicy = lib.mkForce "closed";
          DeviceAllow = lib.mkForce [
            "char-rtc r"
            "/dev/nvidia0 rw"
            "/dev/nvidiactl rw"
            "/dev/nvidia-uvm rw"
            "/dev/nvidia-modeset rw"
            "/dev/dri/card* rw"
            "/dev/dri/renderD* rw"
          ];
        };
      };
    };

in
{
  imports = [
    nix-minecraft.nixosModules.minecraft-servers
  ];

  config = mkMerge [
    (mkIf cfg.enable {
      # nix-minecraft's overlay provides vanillaServers/fabricServers/neoforgeServers/…
      nixpkgs.overlays = [ nix-minecraft.overlay ];

      services.minecraft-servers = {
        enable = true;
        inherit (cfg) eula dataDir openFirewall;
        servers = mapAttrs' mkServer cfg.servers;
      };

      # Per-server resource caps (memory/CPU/scheduler) from the `hardware`
      # option, applied to the generated units.
      systemd.services = lib.mkMerge (
        (map (name: (mkHardwareServiceConfig name cfg.servers.${name}).systemd.services)
          (builtins.attrNames cfg.servers))
        # dataDir + per-server dirs are created by a ROOT oneshot, NOT tmpfiles:
        # systemd-tmpfiles refuses to descend a path whose parent is owned by a
        # non-root user ("Detected unsafe path transition /mnt/data (owned by
        # seanc)") and silently skips the rule. nix-minecraft's tmpfiles rule for
        # ${dataDir}/${name} therefore never runs when dataDir lives under such a
        # parent, leaving the server's WorkingDirectory missing → systemd fails the
        # unit with status=200/CHDIR. This oneshot runs as root before every server
        # so the dirs always exist on fresh machines too.
        ++ [
          {
            "minecraft-server-prepare-dirs" = {
              description = "Create Minecraft server data directories";
              wantedBy = [ "multi-user.target" ];
              before = map (name: "minecraft-server-${name}.service") (builtins.attrNames cfg.servers);
              serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
              };
              script = ''
                ${pkgs.coreutils}/bin/install -d -o minecraft -g minecraft -m 0770 ${cfg.dataDir}
                ${builtins.concatStringsSep "\n" (map (name: ''
                  ${pkgs.coreutils}/bin/install -d -o minecraft -g minecraft -m 0770 ${cfg.dataDir}/${name}
                '') (builtins.attrNames cfg.servers))}
              '';
            };
          }
        ]
      );

      # packDir: owned by the primary user so scp works without sudo, group
      # minecraft so the service user can read the zips. dataDir comes from
      # nix-minecraft's user creation.
      systemd.tmpfiles.rules = [
        "d ${cfg.packDir} 0770 ${me.username} minecraft - -"
      ];

      # Primary user in the minecraft group: dataDir is 0770 minecraft:minecraft
      # (from nix-minecraft), so without group membership the user cannot traverse
      # it to reach packDir — scp to packDir would fail with "Permission denied".
      users.groups.minecraft.members = [ me.username ];
    })

    # ── OpenCode utilities for modpack work ──────────────────────────────────
    # Available on ANY host (client or server) that has opencode enabled, so
    # modpack editing can happen where the modpack is used (e.g. a desktop with
    # Prism Launcher) without running a minecraft server. Tools and skills are
    # sourced from the nixos-minecraft-modpacks input (extracted repo).
    # Gate with my.services.minecraftServer.opencode.enable (default true).
    (mkIf cfg.opencode.enable {
      my.homeManager.extraConfig.my.programs.opencode = {
        tools = {
          packwiz = "${nixos-minecraft-modpacks}/opencode/tools/packwiz.ts";
          packwiz-checksums = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-checksums.ts";
          mc-pack-status = "${nixos-minecraft-modpacks}/opencode/tools/mc-pack-status.ts";
          # Config / patch tooling
          packwiz-config-add = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-config-add.ts";
          packwiz-config-preserve = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-config-preserve.ts";
          packwiz-config-list = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-config-list.ts";
          packwiz-config-diff = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-config-diff.ts";
          packwiz-config-show = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-config-show.ts";
          packwiz-jar-meta = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-jar-meta.ts";
          packwiz-structures = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-structures.ts";
          packwiz-controls = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-controls.ts";
          packwiz-controls-set = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-controls-set.ts";
          packwiz-datapack-add = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-datapack-add.ts";
          packwiz-datapack-remove = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-datapack-remove.ts";
          packwiz-mod-pin = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-mod-pin.ts";
          packwiz-inspect-mod = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-inspect-mod.ts";
          packwiz-update-safe = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-update-safe.ts";
          # Extraction / analysis tools
          packwiz-ore = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-ore.ts";
          packwiz-mobs = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-mobs.ts";
          packwiz-mobspawn = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-mobspawn.ts";
          packwiz-items = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-items.ts";
          packwiz-attributes = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-attributes.ts";
          packwiz-loot = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-loot.ts";
          packwiz-recipes = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-recipes.ts";
          packwiz-item-acquisition = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-item-acquisition.ts";
          packwiz-item-tier = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-item-tier.ts";
          packwiz-mob-combat = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-mob-combat.ts";
          packwiz-mob-tier = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-mob-tier.ts";
          packwiz-analyze = "${nixos-minecraft-modpacks}/opencode/tools/packwiz-analyze.ts";
          mc-prism-log = "${nixos-minecraft-modpacks}/opencode/tools/mc-prism-log.ts";
          mc-run = "${nixos-minecraft-modpacks}/opencode/tools/mc-run.ts";
          mc-install = "${nixos-minecraft-modpacks}/opencode/tools/mc-install.ts";
          # Dedicated-server management
          mc-server = "${nixos-minecraft-modpacks}/opencode/tools/mc-server.ts";
        };
        skills.mc-modpack = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill.md";
        skills.mc-gpu-worldgen = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-gpu-worldgen.md";
        skills.mc-mod-config = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-config.md";
        skills.mc-mod-config-set = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-config-set.md";
        skills.mc-mod-patch = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-patch.md";
        skills.mc-mod-source-patch = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-source-patch.md";
        skills.mc-mod-structures = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-structures.md";
        skills.mc-mod-controls = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-controls.md";
        skills.mc-mod-controls-set = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-controls-set.md";
        skills.mc-server-monitor = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-server-monitor.md";
        # Extraction / analysis skill docs
        skills.mc-mod-ore = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-ore.md";
        skills.mc-mod-mobs = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-mobs.md";
        skills.mc-mod-mobspawn = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-mobspawn.md";
        skills.mc-mod-items = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-items.md";
        skills.mc-mod-attributes = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-attributes.md";
        skills.mc-mod-loot = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-loot.md";
        skills.mc-mod-recipes = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-recipes.md";
        skills.mc-mod-analyze = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-analyze.md";
        skills.mc-mod-item-acquisition = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-item-acquisition.md";
        skills.mc-mod-item-tier = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-item-tier.md";
        skills.mc-mod-combat = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-combat.md";
        skills.mc-mod-tier = builtins.readFile "${nixos-minecraft-modpacks}/opencode/skill-mc-mod-tier.md";
        commands.mc-modpack = "${nixos-minecraft-modpacks}/opencode/commands/mc-modpack.md";
      };
    })
  ];
}
