# =============================================================================
# pack.nix — turn a ThunderStore pack directory into one store derivation
# =============================================================================
# A pack directory is three committed JSON files:
#
#   pack.json       AUTHORED. Which game, which loader, which mods.
#                     { name, game, instance?, mods: { "<ns>-<name>": "<version>" },
#                       exclude?: [...], allowConflicts?: bool, notes? }
#   game.json       GENERATED by `nix run .#thunderstore-sync -- <pack>`.
#                   A frozen snapshot of the game's ecosystem-schema entry plus
#                   the resolved model: steamAppId, steamFolderName,
#                   dataFolderName, exeNames, packageLoader, installRules,
#                   autolistPackageIds, installLoader, loaderPackage,
#                   loaderVersion, loaderPackageRootFolder.
#   checksums.json  GENERATED by `nix run .#thunderstore-checksums -- <pack>`.
#                   { "<ns>-<name>-<version>": { url, sha256, dependencies,
#                     namespace, name, version, isLoader, ... } } — one entry per
#                     declared mod AND per transitive dependency, because
#                     ThunderStore publishes no hash for package zips (the CDN
#                     ETag is an S3 multipart ETag, not a content digest).
#
# The build then:
#   1. fetches every pinned zip as a fixed-output derivation (pkgs.fetchurl),
#   2. unzips them,
#   3. runs lib/route.py, which places each file per the ecosystem's installRules
#      (or the loader's hardcoded routes) into a per-destination overlay,
#   4. emits manifest.json + install-plan.json describing exactly which files
#      belong in the game directory, and ships lib/install.sh beside them.
#
# Nothing is fetched at eval time and nothing at build time except through the
# pinned FODs, so `nix build` on another machine either reproduces byte-identical
# output or fails loudly on a hash mismatch.
#
# Consumed by:
#   - modules/flake-parts/thunderstore.nix → packages."thunderstore-pack-<name>"
#     and apps."thunderstore-install-<name>"
#   - modules/home/thunderstore/config.nix  → home.activation install hook
# =============================================================================

{ lib
, pkgs
, packDir
, name
}:

let
  inherit (lib) concatMapStringsSep optionals;

  loaders = import ./loaders.nix { inherit lib; };

  # ── the three committed files ───────────────────────────────────────────────
  pack = builtins.fromJSON (builtins.readFile "${packDir}/pack.json");
  game =
    if builtins.pathExists "${packDir}/game.json" then
      builtins.fromJSON (builtins.readFile "${packDir}/game.json")
    else
      throw ''
        my.programs.thunderstore: pack ${name} has no game.json.
        Run `nix run .#thunderstore-sync -- ${name}` to fetch the game's ecosystem
        entry (steam appid, loader, install rules) and commit the result.
      '';
  checksums =
    if builtins.pathExists "${packDir}/checksums.json" then
      builtins.fromJSON (builtins.readFile "${packDir}/checksums.json")
    else
      throw ''
        my.programs.thunderstore: pack ${name} has no checksums.json.
        Run `nix run .#thunderstore-checksums -- ${name}` to download and pin every
        mod (and its transitive dependencies), then commit the result.
      '';

  # ── the model, as resolved from the frozen snapshot ────────────────────────
  model = game.model;
  loader = model.packageLoader;
  loaderModel = loaders.byLoader.${loader} or (throw ''
    thunderstore: pack ${name}: game ${model.label} uses loader "${loader}", which
    modules/home/thunderstore/lib/loaders.nix does not model.
    Model it there (or pick a different game) before building this pack.
    Modelled loaders: ${toString (lib.attrNames loaders.byLoader)}
  '');

  # Family check: install-rule-driven loaders need the game's installRules.
  installRules =
    if loaderModel.family == "installRules" && (model.installRules or [ ]) == [ ] then
      throw ''
        thunderstore: pack ${name}: loader "${loader}" is install-rule driven but
        game ${model.label} declares no installRules, so no mod file could be
        placed. This is an ecosystem data gap — report it upstream
        (thunderstore-io/ecosystem-schema) or drop the pack.
      ''
    else
      model.installRules or [ ];

  # ── which packages get installed ───────────────────────────────────────────
  # checksums.json already holds the transitive dependency closure (resolved at
  # pin time), so it — not pack.json's `mods` — decides what is fetched.
  excluded = pack.exclude or [ ];
  allEntries = lib.attrValues checksums;
  isExcluded = entry: lib.elem "${entry.namespace}-${entry.name}" excluded;

  installLoader = model.installLoader or false;
  loaderId =
    if installLoader && model.loaderPackage != null then
      "${model.loaderPackage}-${model.loaderVersion}"
    else
      null;
  loaderPin =
    if loaderId == null then
      null
    else
      checksums.${loaderId} or (throw ''
        thunderstore: pack ${name}: the loader pack is enabled but not pinned.
        Expected "${loaderId}" in checksums.json — re-run
        `nix run .#thunderstore-checksums -- ${name}`, or set "installLoader": false
        in pack.json to manage the loader yourself.
      '');

  allModPins = builtins.filter (e: !(e.isLoader or false) && !isExcluded e) allEntries;

  # Every mod the user declared must actually be pinned, or the build would
  # silently install less than pack.json promises.
  modPins =
    let
      declared = lib.attrNames (pack.mods or { });
      missing = lib.filter
        (
          full: !(lib.any (e: "${e.namespace}-${e.name}" == full) allModPins)
        )
        declared;
    in
    if missing == [ ] then
      allModPins
    else
      throw ''
        thunderstore: pack ${name}: pack.json declares mods that are not in
        checksums.json (or were excluded):
          ${lib.concatStringsSep "\n  " missing}
        Re-run `nix run .#thunderstore-checksums -- ${name}`.
      '';

  # ── one fetchurl per pinned package ────────────────────────────────────────
  fetched = lib.listToAttrs (
    map
      (entry: {
        name = entry.id;
        value = pkgs.fetchurl {
          name = "${entry.namespace}-${entry.name}-${entry.version}";
          url = entry.url;
          sha256 =
            entry.sha256 or (throw ''
              thunderstore: pack ${name}: ${entry.id} has no "sha256" in
              checksums.json. Re-run `nix run .#thunderstore-checksums -- ${name}`.
            '');
        };
      })
      (optionals (loaderPin != null) [ loaderPin ] ++ modPins)
  );

  entryFor = kind: entry: {
    inherit kind;
    inherit (entry) id modName dependencies;
    rootFolder =
      if kind == "loader" then (model.loaderPackageRootFolder or "") else "";
    srcDir = "zips/${entry.id}";
  };

  entries =
    optionals (loaderPin != null) [
      (entryFor "loader" (loaderPin // { modName = model.loaderPackage; dependencies = [ ]; }))
    ]
    ++ map (entryFor "mod") (
      map (e: e // { modName = e.name; }) modPins
    );

  # ── the routing spec handed to lib/route.py ────────────────────────────────
  spec = pkgs.writeText "thunderstore-spec-${name}.json" (builtins.toJSON {
    inherit loader installRules;
    pack = {
      inherit (pack) name;
      game = model.label;
    };
    game = model;
    loaders = loaders.toJson;
    relativeFileExclusions = model.relativeFileExclusions or null;
    allowConflicts = pack.allowConflicts or false;
    profileDir = "profile";
    planOut = "install-plan.json";
    manifestOut = "routed.json";
    entries = entries;
  });

  packJson = pkgs.writeText "thunderstore-pack-${name}.json" (builtins.toJSON pack);
  modelJson = pkgs.writeText "thunderstore-model-${name}.json" (builtins.toJSON model);

  # ── the build ──────────────────────────────────────────────────────────────
  routing = pkgs.runCommand "thunderstore-pack-${name}"
    {
      nativeBuildInputs = [ pkgs.unzip pkgs.python3 ];
      passthru = {
        inherit name;
        game = model.label;
        gameDisplayName = model.displayName;
        appid = model.steamAppId;
        inherit loader;
        mods = map (e: e.id) modPins;
        packages = lib.attrNames fetched;
      };
    }
    ''
      cp ${spec} spec.json

      mkdir -p zips
      ${concatMapStringsSep "\n"
        (entry: ''
          mkdir -p "zips/${entry.id}"
          unzip -q -o ${fetched.${entry.id}} -d "zips/${entry.id}"
        '')
        entries}

      ${pkgs.python3}/bin/python3 ${./route.py} spec.json

      # lib/install.sh resolves the profile as <manifest dir>/profile, so keep
      # that layout exact.
      mkdir -p "$out/profile"
      cp -r profile/. "$out/profile/"
      cp install-plan.json "$out/install-plan.json"
      cp routed.json "$out/routed.json"
      cp ${./install.sh} "$out/install.sh"
      chmod +x "$out/install.sh"

      # manifest.json is what lib/install.sh consumes: pack + game identity plus
      # the exact file list, each entry carrying both hash forms.
      ${pkgs.jq}/bin/jq -n \
        --slurpfile pack ${packJson} \
        --slurpfile game ${modelJson} \
        --slurpfile plan install-plan.json \
        '{
           pack: ($pack[0] | {name, game, notes}),
           game: $game[0],
           loader: $plan[0].loader,
           conflicts: ($plan[0].conflicts // []),
           notes: ($plan[0].notes // []),
           files: $plan[0].files,
           dirs: $plan[0].dirs
         }' > "$out/manifest.json"
    '';

  installScript = pkgs.writeShellScriptBin "thunderstore-install-${name}" ''
    set -euo pipefail
    export PATH=${pkgs.coreutils}/bin:${pkgs.findutils}/bin:${pkgs.gnused}/bin:$PATH
    exec ${routing}/install.sh ${routing}/manifest.json "$@"
  '';

in
{
  inherit routing installScript fetched;

  # The public value: the built pack (profile + manifest + installer).
  package = routing;
}
