name = "Test Modpack"
author = "Cairnstew"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c56f2a97bfe38810559b505eeb19597c7722512ff38a30c40376221ea19588"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
datapack-folder = "config/paxi/datapacks"
