name = "Test Modpack"
author = "Cairnstew"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31accc23c8f7a76c7f694364d0657ca5f8e6bf0cba70a67080bbacbc5036983c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
datapack-folder = "config/paxi/datapacks"
