name = "DragonTech"
author = "Cairnstew"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac9bc03bed31237cae74a0854701e3e0a3e3b9f984c2a0b8a059b5c7c484aca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
datapack-folder = "config/paxi/datapacks"
