plugins {
    id 'net.neoforged.moddev' version '2.0.72'
}

version = '1.0.0'
group = 'dev.seanc'
base { archivesName = 'item-components-dump' }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

neoForge {
    version = '21.1.238'

    mods {
        itemcomponentsdump {
            sourceSet sourceSets.main
        }
    }
}

tasks.named('jar', Jar) {
    archiveClassifier = ''
}
