#!/usr/bin/env bash
# Re-vendors the opencode-ensemble dist artifact.
#
# Usage:
#   tools/revendor-opencode-ensemble.sh <path-to-dist/index.js> <version>
#
# This is the ONLY legitimate way to update the vendored artifact
# (modules/home/opencode/vendor/opencode-ensemble-*-dist.js). It:
#   1. prepends the vendor/BANNER header to the new dist,
#   2. copies it to vendor/opencode-ensemble-<version>-dist.js,
#   3. recomputes the sha256 and rewrites vendor/opencode-ensemble.sha256
#      IN THE SAME OPERATION.
#
# There is no separate manual hash-edit step for a legitimate update — the
# recorded hash changes only here, so tests/opencode-ensemble-vendor_test.nix
# can trust it. Never edit the vendored bundle or the .sha256 file by hand:
# local edits are the exact brute-force failure mode the hash-guard exists to
# catch (develop upstream via team_spawn(space="ensemble"), then re-vendor).
#
# Remaining manual FORK.md steps after this script (cannot be automated):
# update fork.nix to reference the new vendor file and re-derive patch anchors;
# then run `nix run .#nixtests-run` + a live spawn verification.
set -euo pipefail

DIST="${1:?usage: tools/revendor-opencode-ensemble.sh <dist/index.js> <version>}"
VERSION="${2:?usage: tools/revendor-opencode-ensemble.sh <dist/index.js> <version>}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR_DIR="$ROOT/modules/home/opencode/vendor"
BANNER="$VENDOR_DIR/BANNER"
TARGET="$VENDOR_DIR/opencode-ensemble-$VERSION-dist.js"
HASH_FILE="$VENDOR_DIR/opencode-ensemble.sha256"

[[ -f "$DIST" ]] || { echo "error: dist not found: $DIST" >&2; exit 1; }
[[ -f "$BANNER" ]] || { echo "error: vendor banner not found: $BANNER" >&2; exit 1; }

# Sanity: the new dist must be valid ESM (mirrors fork.nix's node --check).
if command -v node >/dev/null 2>&1; then
  node --check "$DIST"
else
  echo "warning: node not on PATH — skipping node --check (fork.nix will catch it)"
fi

# Prepend banner + copy in one commit-ready operation.
cat "$BANNER" "$DIST" > "$TARGET"

# Recompute hash of the FINAL committed bytes (banner included) and rewrite
# the hash file in the same operation — no separate manual hash-edit step.
HASH="$(sha256sum "$TARGET" | awk '{print $1}')"
cat > "$HASH_FILE" <<EOF
# Auto-generated by tools/revendor-opencode-ensemble.sh — do not edit by hand.
# Regenerate ONLY via that script (it rewrites this file in the same operation
# as the vendored dist). Hashes the banner-prefixed artifact in vendor/.
filename=$(basename "$TARGET")
sha256=$HASH
EOF

echo "vendored:  $TARGET"
echo "hash file: $HASH_FILE (sha256=$HASH)"
echo
echo "REMINDER — still manual per modules/home/opencode/FORK.md:"
echo "  1. update fork.nix to reference the new vendor file"
echo "  2. re-run the patch; re-derive any moved anchors"
echo "  3. run: nix run .#nixtests-run  + live spawn-batch verification"
echo "Commit the .dist.js + .sha256 changes together in one commit."