// ============================================================================
// Structure Helper  —  by ScalarVector1
// https://steamcommunity.com/workshop/filedetails/?id=3178462942
//
// Prefab structure placement API. Load .schematic files generated by
// Structure Helper and place them in the world.
//
// Integration pattern: Mod.Call (preferred) or direct reference
// ============================================================================
//
// USAGE:
//   1. Uncomment the block below.
//   2. Place .schematic files in YourMod/Assets/Structures/.
//   3. Call PlaceStructure() during world generation or at runtime.
//
// ============================================================================
/*
using Microsoft.Xna.Framework;
using Terraria.ModLoader;

namespace YourMod.LibIntegrations;

public static class StructureHelperIntegration
{
    private static Mod _sh;

    public static void Load()
    {
        if (!ModLoader.TryGetMod("StructureHelper", out _sh))
            return;
    }

    /// <summary>Place a .schematic at the given position.</summary>
    public static bool PlaceStructure(string schematicPath, Point origin)
    {
        return _sh?.Call("PlaceStructure", schematicPath, origin) as bool? ?? false;
    }

    /// <summary>Generate a structure during world gen.</summary>
    public static void GenerateStructure(string schematicPath, Point origin)
    {
        _sh?.Call("GenerateStructure", schematicPath, origin);
    }

    /// <summary>Export a structure from the current world to a file.</summary>
    public static void SaveStructure(string schematicPath, Rectangle area)
    {
        _sh?.Call("SaveStructure", schematicPath, area);
    }
}
*/
