# =============================================================================
# Server Hardware Configuration
# =============================================================================
# Physical Machine: AMD-based headless server (Beelink/mini PC or similar)
#   - CPU: AMD (kvm-amd kernel module)
#   - Storage: NVMe SSD + AHCI SATA support
#   - Network: Wired ethernet (DHCP via networking.useDHCP)
#
# Generation Method:
#   Generated by `nixos-generate-config` during initial installation.
#   Do not edit manually — changes will be lost on regeneration.
#
# Filesystem Layout:
#   - /     : ext4 on /dev/disk/by-uuid/4079b1c2-d485-43f1-9e82-e7fa1ad30a09
#   - /boot : vfat (EFI) on /dev/disk/by-uuid/AB94-2222
#
# Non-standard Configuration:
#   - DHCP enabled on all interfaces (headless server, IP assigned by router)
#   - USB storage modules for external drives/installation media
#   - No swap device configured
# =============================================================================

# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-uuid/4079b1c2-d485-43f1-9e82-e7fa1ad30a09";
    fsType = "ext4";
  };

  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-uuid/AB94-2222";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
