# =============================================================================
# Laptop Hardware Configuration
# =============================================================================
# Physical Machine: Intel-based laptop (likely ThinkPad or similar)
#   - CPU: Intel (kvm-intel kernel module)
#   - Storage: NVMe SSD
#   - Connectivity: USB-C/Thunderbolt
#
# Generation Method:
#   Generated by `nixos-generate-config` during initial installation.
#   Do not edit manually — changes will be lost on regeneration.
#
# Filesystem Layout:
#   - /     : ext4 on /dev/disk/by-uuid/220dc7c6-6a08-446d-ab6f-c9ce5638b022
#   - /boot : vfat (EFI) on /dev/disk/by-uuid/BE6C-86F6
#
# Non-standard Configuration:
#   - No swap device configured
#   - Uses not-detected.nix for hardware detection
# =============================================================================

# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # fileSystems and swapDevices are defined by configurations/nixos/laptop/disk-config.nix (disko).
  # After nixos-anywhere generates a new hardware config, nixos-generate-config will
  # produce fileSystems entries with lib.mkDefault that coexist with disko.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
