# =============================================================================
# secrets.nix — Agenix Secret Definitions
# =============================================================================
# AUTO-GENERATED: The attrset below is generated by `nix run .#secrets-generate -- --write`.
# The let-block (host keys, user keys) is hand-maintained.
#
# To add a new secret:
#   1. nix run .#secrets-edit path/to/secret.age
#   2. Add catalog entry in modules/nixos/secrets/catalog.nix
#   3. nix run .#secrets-generate -- --write
#
# To add a new host:
#   1. Capture the SSH host key: cat /etc/ssh/ssh_host_ed25519_key.pub
#   2. Add it to the `systems` list below
#   3. Run: cd secrets && nix develop && agenix-rekey
# =============================================================================

let
  config = import ../config.nix;
  users = [ config.me.sshKey ];

  # SSH host keys for decrypting secrets on each machine
  laptop = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIETE96NnwPAZ0n5y6XcCzoErkrAhulUht/Hho0V829Qy root@laptop";
  server = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJXLC3S2pEuIchrWMtmWiTaJOA+U02HVyRczRNbRjMX root@nixos";
  wsl = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAKZIYbM8ac+hHEAvvScLq2lHtAHi44Zlvlew/QYU3H0 root@wsl";

  desktop = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWiP0JxNaeWS30gzg4A2zLnSRdZutWzCP0mjZit7/De root@desktop";
  systems = [ laptop server wsl desktop ];
  all = users ++ systems;
in
{
  "ai/clarifai-pat.age".publicKeys = all;
  "ai/deepinfra-key.age".publicKeys = all;
  "ai/groq-token.age".publicKeys = all;
  "ai/huggingface-token.age".publicKeys = all;
  "ai/opencode-token.age".publicKeys = all;
  "cachix/nixos-config-cache-token.age".publicKeys = all;
  "cloud/aws/aws-cloud.age".publicKeys = all;
  "cloud/aws/aws-lab-ssh-key.age".publicKeys = all;
  "cloud/aws/aws-ssh-key.age".publicKeys = all;
  "cloud/aws/aws-ssh-pub-key.age".publicKeys = all;
  "cloud/gcloud/gcloud-auth.age".publicKeys = all;
  "github/github-token.age".publicKeys = all;
  "github/repos/github-token-nixos-config.age".publicKeys = all;
  "github/repos/github-token-obsidian.age".publicKeys = all;
  "mail/gmail/better-email-password.age".publicKeys = all;
  "tailscale/tailscale-authkey.age".publicKeys = all;
  "tailscale/tailscale-oauthkey.age".publicKeys = all;
  "tailscale/tailscale-ssh-key.age".publicKeys = all;
  "windows-password.age".publicKeys = all;


}
